name: "Deploy to Nuget"

on:
  push:
    #branches: [ master ]
    tags:
      - "v*"

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\packages
  PROJECT_PATH: GreatIdeasExtensions.sln

jobs:
  deploy:
    name: Deploy and Push to Nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.x"
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Project
        run: dotnet build --tl --configuration Release

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack Project
        run: dotnet pack --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      # - name: Remove NuGet Packages with name Sample
      #   run: |
      #     find ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -type f -name '*Sample*' -exec rm -f {} +

      - name: Push to Nuget
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
